/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.commsen.liferay.multidevice.service.base;

import com.commsen.liferay.multidevice.model.ThemeRule;
import com.commsen.liferay.multidevice.service.ThemeRuleLocalService;
import com.commsen.liferay.multidevice.service.ThemeRuleService;
import com.commsen.liferay.multidevice.service.persistence.ThemeRulePersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.annotation.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the theme rule local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.commsen.liferay.multidevice.service.impl.ThemeRuleLocalServiceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. Always use {@link com.commsen.liferay.multidevice.service.ThemeRuleLocalServiceUtil} to access the theme rule local service.
 * </p>
 *
 * @author Milen Dyankov
 * @see com.commsen.liferay.multidevice.service.impl.ThemeRuleLocalServiceImpl
 * @see com.commsen.liferay.multidevice.service.ThemeRuleLocalServiceUtil
 * @generated
 */
public abstract class ThemeRuleLocalServiceBaseImpl
	implements ThemeRuleLocalService {
	/**
	 * Adds the theme rule to the database. Also notifies the appropriate model listeners.
	 *
	 * @param themeRule the theme rule to add
	 * @return the theme rule that was added
	 * @throws SystemException if a system exception occurred
	 */
	public ThemeRule addThemeRule(ThemeRule themeRule)
		throws SystemException {
		themeRule.setNew(true);

		return themeRulePersistence.update(themeRule, false);
	}

	/**
	 * Creates a new theme rule with the primary key. Does not add the theme rule to the database.
	 *
	 * @param rid the primary key for the new theme rule
	 * @return the new theme rule
	 */
	public ThemeRule createThemeRule(long rid) {
		return themeRulePersistence.create(rid);
	}

	/**
	 * Deletes the theme rule with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param rid the primary key of the theme rule to delete
	 * @throws PortalException if a theme rule with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteThemeRule(long rid)
		throws PortalException, SystemException {
		themeRulePersistence.remove(rid);
	}

	/**
	 * Deletes the theme rule from the database. Also notifies the appropriate model listeners.
	 *
	 * @param themeRule the theme rule to delete
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteThemeRule(ThemeRule themeRule) throws SystemException {
		themeRulePersistence.remove(themeRule);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return themeRulePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return themeRulePersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @param orderByComparator the comparator to order the results by
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return themeRulePersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Counts the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return themeRulePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Gets the theme rule with the primary key.
	 *
	 * @param rid the primary key of the theme rule to get
	 * @return the theme rule
	 * @throws PortalException if a theme rule with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public ThemeRule getThemeRule(long rid)
		throws PortalException, SystemException {
		return themeRulePersistence.findByPrimaryKey(rid);
	}

	/**
	 * Gets a range of all the theme rules.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of theme rules to return
	 * @param end the upper bound of the range of theme rules to return (not inclusive)
	 * @return the range of theme rules
	 * @throws SystemException if a system exception occurred
	 */
	public List<ThemeRule> getThemeRules(int start, int end)
		throws SystemException {
		return themeRulePersistence.findAll(start, end);
	}

	/**
	 * Gets the number of theme rules.
	 *
	 * @return the number of theme rules
	 * @throws SystemException if a system exception occurred
	 */
	public int getThemeRulesCount() throws SystemException {
		return themeRulePersistence.countAll();
	}

	/**
	 * Updates the theme rule in the database. Also notifies the appropriate model listeners.
	 *
	 * @param themeRule the theme rule to update
	 * @return the theme rule that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public ThemeRule updateThemeRule(ThemeRule themeRule)
		throws SystemException {
		themeRule.setNew(false);

		return themeRulePersistence.update(themeRule, true);
	}

	/**
	 * Updates the theme rule in the database. Also notifies the appropriate model listeners.
	 *
	 * @param themeRule the theme rule to update
	 * @param merge whether to merge the theme rule with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the theme rule that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public ThemeRule updateThemeRule(ThemeRule themeRule, boolean merge)
		throws SystemException {
		themeRule.setNew(false);

		return themeRulePersistence.update(themeRule, merge);
	}

	/**
	 * Gets the theme rule local service.
	 *
	 * @return the theme rule local service
	 */
	public ThemeRuleLocalService getThemeRuleLocalService() {
		return themeRuleLocalService;
	}

	/**
	 * Sets the theme rule local service.
	 *
	 * @param themeRuleLocalService the theme rule local service
	 */
	public void setThemeRuleLocalService(
		ThemeRuleLocalService themeRuleLocalService) {
		this.themeRuleLocalService = themeRuleLocalService;
	}

	/**
	 * Gets the theme rule remote service.
	 *
	 * @return the theme rule remote service
	 */
	public ThemeRuleService getThemeRuleService() {
		return themeRuleService;
	}

	/**
	 * Sets the theme rule remote service.
	 *
	 * @param themeRuleService the theme rule remote service
	 */
	public void setThemeRuleService(ThemeRuleService themeRuleService) {
		this.themeRuleService = themeRuleService;
	}

	/**
	 * Gets the theme rule persistence.
	 *
	 * @return the theme rule persistence
	 */
	public ThemeRulePersistence getThemeRulePersistence() {
		return themeRulePersistence;
	}

	/**
	 * Sets the theme rule persistence.
	 *
	 * @param themeRulePersistence the theme rule persistence
	 */
	public void setThemeRulePersistence(
		ThemeRulePersistence themeRulePersistence) {
		this.themeRulePersistence = themeRulePersistence;
	}

	/**
	 * Gets the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Gets the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Gets the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Gets the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Gets the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Gets the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Gets the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query to perform
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = themeRulePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = ThemeRuleLocalService.class)
	protected ThemeRuleLocalService themeRuleLocalService;
	@BeanReference(type = ThemeRuleService.class)
	protected ThemeRuleService themeRuleService;
	@BeanReference(type = ThemeRulePersistence.class)
	protected ThemeRulePersistence themeRulePersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}